using UcBuild.Toolchain;

namespace UcBuild;

/// <summary>
/// Provides a means to configure the settings of a build operation
/// </summary>
public sealed class BuildTarget
{
	/// <summary>
	/// Gets or sets a value that controls if listing files are generated by the compiler
	/// </summary>
	public bool GenerateListings { get; set; }

	/// <summary>
	/// Gets or initializes the name of the target
	/// </summary>
	public required string Name { get; init; }

	/// <summary>
	/// Gets or initializes the path of the directory where build artifacts are stored for the
	/// target
	/// </summary>
	public required string ArtifactDirectory { get; init; }
	
	/// <summary>
	/// Gets the options passed to the compiler
	/// </summary>
	public List<string> CompilerOptions { get; private init; } = [];
	
	/// <summary>
	/// Gets the include paths passed to the compiler
	/// </summary>
	public List<string> CompilerIncludes { get; private init; } = [];

	/// <summary>
	/// Gets the defines passed to the compiler
	/// </summary>
	public List<string> ComilerDefines { get; private init; } = [];

	/// <summary>
	/// Gets or sets the toolchain used to build the project
	/// </summary>
	public IToolchain Toolchain { get; set; } = Toolchains.Default;
}